export const assets = {
  splash: require('../../assets/splash.gif'),
  bell: require('../../assets/icons/bell.png'),
  chevron: require('../../assets/icons/chevron.png'),
  back: require('../../assets/icons/back.png'),
  edit: require('../../assets/icons/edit.png'),
  hamburger: require('../../assets/icons/Hamburger_icon.png'),
  logo: require('../../assets/images/logo.png'),
  logoWhite: require('../../assets/images/logo-white.png'),
  vlogo: require('../../assets/vlogo.png'),
  mainLogo: require('../../assets/icon.png'),
  bg: require('../../assets/images/chbg.jpg'),
  loginBg: require('../../assets/images/loginbg.png'),
  forgetBg: require('../../assets/images/forgot_bg.jpeg'),
  clock: require('../../assets/icons/clock.png'),
  shake: require('../../assets/images/shake.png'),
};
